### ISSUE TITLE
示例代码bbox多加了[]

### ISSUE THREAD

**Issue by Liu-yixi** [CASIA-IVA-Lab/FastSAM#128]

**Comment by yangguanghaiann** [comment]
/home/pcl/anaconda3/envs/FastSAM/bin/python /home/pcl/yolo/FastSAM/1.py

image 1/1 /home/pcl/yolo/FastSAM/images/dogs.jpg: 576x1024 16 objects, 273.5ms
Speed: 2.9ms preprocess, 273.5ms inference, 42.2ms postprocess per image at shape (1, 3, 1024, 1024)
Traceback (most recent call last):
  File "/home/pcl/yolo/FastSAM/1.py", line 14, in <module>
    ann = prompt_process.box_prompt(bbox=[[200, 200, 300, 300]])
  File "/home/pcl/yolo/FastSAM/fastsam/prompt.py", line 385, in box_prompt
    assert (bbox[2] != 0 and bbox[3] != 0)
IndexError: list index out of range


最后的示例，运行是这个结果，你是说的这个问题吗？错误在# bbox default shape [0,0,0,0] -> [x1,y1,x2,y2]
ann = prompt_process.box_prompt(bbox=[[200, 200, 300, 300]])此行代码，注释掉此行代码可以运行。报错为超出范围，不知道啥原因，你知道咋解决吗？

**Comment by Liu-yixi** [comment]
或者改为 ann = prompt_process.box_prompt(bboxs=[[200, 200, 300, 300]])

**Comment by yangguanghaiann** [comment]
好的，谢谢

**Comment by ErolCitak** [comment]
We have just found the correct way to achieve this problem:

The only thing you need to change is the argument name;

Change this one: ann = prompt_process.box_prompt(bbox=[[500,750, 3700, 2800]])
To: ann = prompt_process.box_prompt(bboxes=[[200, 200, 300, 300]])

Please pay attention to argument name: "bbox" --> "bboxes"
