### ISSUE TITLE
Can this project be exported to ONNX?

### ISSUE THREAD

**Issue by SonwYang** [CASIA-IVA-Lab/FastSAM#16]
I want to use this pro to deploy.

**Comment by zxDeepDiver** [comment]
Yes, the tutorials is [here](https://docs.ultralytics.com/modes/export/).

**Comment by wavelet2008** [comment]
(face19) lan@lan:~/sdf/FastSAM$ yolo export model=FastSAM-s.pt  format=onnx
Traceback (most recent call last):
  File "/home/lan/anaconda3/envs/face19/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/lan/anaconda3/envs/face19/lib/python3.9/site-packages/ultralytics/yolo/cfg/__init__.py", line 375, in entrypoint
    model = SAM(model)
  File "/home/lan/anaconda3/envs/face19/lib/python3.9/site-packages/ultralytics/vit/sam/model.py", line 19, in __init__
    self.model = build_sam(model)
  File "/home/lan/anaconda3/envs/face19/lib/python3.9/site-packages/ultralytics/vit/sam/build.py", line 125, in build_sam
    raise FileNotFoundError(f'{ckpt} is not a supported sam model. Available models are: \n {sam_model_map.keys()}')
FileNotFoundError: FastSAM-s.pt is not a supported sam model. Available models are: 
 dict_keys(['sam_h.pt', 'sam_l.pt', 'sam_b.pt'])
