### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by Linaom1214** [CASIA-IVA-Lab/FastSAM#167]
can you provide more detials about model training? 

I use the coco128-seg. which modify the `sam.yaml`

```
 # Ultralytics YOLO 🚀, AGPL-3.0 license
# COCO128-seg dataset https://www.kaggle.com/ultralytics/coco128 (first 128 images from COCO train2017) by Ultralytics
# Example usage: yolo train data=coco128.yaml
# parent
# ├── ultralytics
# └── datasets
#     └── coco128-seg  ← downloads here (7 MB)


# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/coco128-seg  # dataset root dir
train: images/train2017  # train images (relative to 'path') 128 images
val: images/train2017  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes
names:
  0: object


# Download script/URL (optional)
download: https://ultralytics.com/assets/coco128-seg.zip
```

but I got the error 
```
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000009.jpg: ignoring corrupt image/label: Label class 50 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000025.jpg: ignoring corrupt image/label: Label class 23 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000030.jpg: ignoring corrupt image/label: Label class 75 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000034.jpg: ignoring corrupt image/label: Label class 22 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000036.jpg: ignoring corrupt image/label: Label class 25 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000042.jpg: ignoring corrupt image/label: Label class 16 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000049.jpg: ignoring corrupt image/label: Label class 58 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000061.jpg: ignoring corrupt image/label: Label class 20 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000064.jpg: ignoring corrupt image/label: Label class 74 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000071.jpg: ignoring corrupt image/label: Label class 7 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000072.jpg: ignoring corrupt image/label: Label class 23 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000073.jpg: ignoring corrupt image/label: Label class 3 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000074.jpg: ignoring corrupt image/label: Label class 16 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000077.jpg: ignoring corrupt image/label: Label class 36 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000078.jpg: ignoring corrupt image/label: Label class 74 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000081.jpg: ignoring corrupt image/label: Label class 4 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000086.jpg: ignoring corrupt image/label: Label class 26 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000089.jpg: ignoring corrupt image/label: Label class 73 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000092.jpg: ignoring corrupt image/label: Label class 55 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000094.jpg: ignoring corrupt image/label: Label class 7 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000109.jpg: ignoring corrupt image/label: Label class 16 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000110.jpg: ignoring corrupt image/label: Label class 60 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000113.jpg: ignoring corrupt image/label: Label class 60 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000127.jpg: ignoring corrupt image/label: Label class 73 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000133.jpg: ignoring corrupt image/label: Label class 77 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000136.jpg: ignoring corrupt image/label: Label class 23 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000138.jpg: ignoring corrupt image/label: Label class 75 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000142.jpg: ignoring corrupt image/label: Label class 60 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000143.jpg: ignoring corrupt image/label: Label class 14 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000144.jpg: ignoring corrupt image/label: Label class 23 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000149.jpg: ignoring corrupt image/label: Label class 33 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000151.jpg: ignoring corrupt image/label: Label class 11 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000154.jpg: ignoring corrupt image/label: Label class 22 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000164.jpg: ignoring corrupt image/label: Label class 72 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000165.jpg: ignoring corrupt image/label: Label class 76 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000192.jpg: ignoring corrupt image/label: Label class 34 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000194.jpg: ignoring corrupt image/label: Label class 53 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000196.jpg: ignoring corrupt image/label: Label class 60 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000201.jpg: ignoring corrupt image/label: Label class 31 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000208.jpg: ignoring corrupt image/label: Label class 79 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000241.jpg: ignoring corrupt image/label: Label class 65 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000247.jpg: ignoring corrupt image/label: Label class 4 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000257.jpg: ignoring corrupt image/label: Label class 26 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000260.jpg: ignoring corrupt image/label: Label class 28 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000263.jpg: ignoring corrupt image/label: Label class 20 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000283.jpg: ignoring corrupt image/label: Label class 60 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000294.jpg: ignoring corrupt image/label: Label class 74 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000307.jpg: ignoring corrupt image/label: Label class 29 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000308.jpg: ignoring corrupt image/label: Label class 74 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000309.jpg: ignoring corrupt image/label: Label class 77 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000312.jpg: ignoring corrupt image/label: Label class 20 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000315.jpg: ignoring corrupt image/label: Label class 56 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000321.jpg: ignoring corrupt image/label: Label class 52 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000322.jpg: ignoring corrupt image/label: Label class 29 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000326.jpg: ignoring corrupt image/label: Label class 40 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000328.jpg: ignoring corrupt image/label: Label class 73 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000332.jpg: ignoring corrupt image/label: Label class 51 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000338.jpg: ignoring corrupt image/label: Label class 74 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000349.jpg: ignoring corrupt image/label: Label class 58 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000357.jpg: ignoring corrupt image/label: Label class 35 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000359.jpg: ignoring corrupt image/label: Label class 9 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000360.jpg: ignoring corrupt image/label: Label class 31 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000368.jpg: ignoring corrupt image/label: Label class 32 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000370.jpg: ignoring corrupt image/label: Label class 50 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000382.jpg: ignoring corrupt image/label: Label class 30 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000384.jpg: ignoring corrupt image/label: Label class 74 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000387.jpg: ignoring corrupt image/label: Label class 67 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000389.jpg: ignoring corrupt image/label: Label class 27 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000394.jpg: ignoring corrupt image/label: Label class 29 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000395.jpg: ignoring corrupt image/label: Label class 67 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000397.jpg: ignoring corrupt image/label: Label class 60 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000400.jpg: ignoring corrupt image/label: Label class 16 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000404.jpg: ignoring corrupt image/label: Label class 8 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000415.jpg: ignoring corrupt image/label: Label class 38 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000419.jpg: ignoring corrupt image/label: Label class 38 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000428.jpg: ignoring corrupt image/label: Label class 55 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000431.jpg: ignoring corrupt image/label: Label class 38 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000436.jpg: ignoring corrupt image/label: Label class 54 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000438.jpg: ignoring corrupt image/label: Label class 54 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000443.jpg: ignoring corrupt image/label: Label class 65 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000446.jpg: ignoring corrupt image/label: Label class 73 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000450.jpg: ignoring corrupt image/label: Label class 60 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000459.jpg: ignoring corrupt image/label: Label class 27 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000471.jpg: ignoring corrupt image/label: Label class 5 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000472.jpg: ignoring corrupt image/label: Label class 4 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000474.jpg: ignoring corrupt image/label: Label class 35 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000486.jpg: ignoring corrupt image/label: Label class 72 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000488.jpg: ignoring corrupt image/label: Label class 35 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000490.jpg: ignoring corrupt image/label: Label class 36 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000491.jpg: ignoring corrupt image/label: Label class 77 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000502.jpg: ignoring corrupt image/label: Label class 21 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000510.jpg: ignoring corrupt image/label: Label class 13 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000514.jpg: ignoring corrupt image/label: Label class 59 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000520.jpg: ignoring corrupt image/label: Label class 14 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000529.jpg: ignoring corrupt image/label: Label class 3 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000531.jpg: ignoring corrupt image/label: Label class 38 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000532.jpg: ignoring corrupt image/label: Label class 26 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000536.jpg: ignoring corrupt image/label: Label class 67 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000540.jpg: ignoring corrupt image/label: Label class 9 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000542.jpg: ignoring corrupt image/label: Label class 27 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000544.jpg: ignoring corrupt image/label: Label class 35 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000560.jpg: ignoring corrupt image/label: Label class 71 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000562.jpg: ignoring corrupt image/label: Label class 79 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000564.jpg: ignoring corrupt image/label: Label class 56 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000569.jpg: ignoring corrupt image/label: Label class 33 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000572.jpg: ignoring corrupt image/label: Label class 28 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000575.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000581.jpg: ignoring corrupt image/label: Label class 16 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000584.jpg: ignoring corrupt image/label: Label class 51 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000589.jpg: ignoring corrupt image/label: Label class 29 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000590.jpg: ignoring corrupt image/label: Label class 71 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000595.jpg: ignoring corrupt image/label: Label class 62 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000597.jpg: ignoring corrupt image/label: Label class 20 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000599.jpg: ignoring corrupt image/label: Label class 65 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000605.jpg: ignoring corrupt image/label: Label class 60 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000612.jpg: ignoring corrupt image/label: Label class 77 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000620.jpg: ignoring corrupt image/label: Label class 72 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000623.jpg: ignoring corrupt image/label: Label class 77 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000625.jpg: ignoring corrupt image/label: Label class 29 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000626.jpg: ignoring corrupt image/label: Label class 74 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000629.jpg: ignoring corrupt image/label: Label class 3 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000634.jpg: ignoring corrupt image/label: Label class 36 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000636.jpg: ignoring corrupt image/label: Label class 61 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000641.jpg: ignoring corrupt image/label: Label class 5 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000643.jpg: ignoring corrupt image/label: Label class 77 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/train_and_validation/datasets/coco128-seg/images/train2017/000000000650.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0
train: New cache created: /content/train_and_validation/datasets/coco128-seg/labels/train2017.cache
Traceback (most recent call last):
  File "/content/train_and_validation/train_sa.py", line 4, in <module>
    model.train(data="sa.yaml", \
  File "/content/train_and_validation/ultralytics-d8701b42caeb9f7f1de5fd45e7c3f3cf1724ebb6/ultralytics/yolo/engine/model.py", line 373, in train
    self.trainer.train()
  File "/content/train_and_validation/ultralytics-d8701b42caeb9f7f1de5fd45e7c3f3cf1724ebb6/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/content/train_and_validation/ultralytics-d8701b42caeb9f7f1de5fd45e7c3f3cf1724ebb6/ultralytics/yolo/engine/trainer.py", line 275, in _do_train
    self._setup_train(world_size)
  File "/content/train_and_validation/ultralytics-d8701b42caeb9f7f1de5fd45e7c3f3cf1724ebb6/ultralytics/yolo/engine/trainer.py", line 239, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
  File "/content/train_and_validation/ultralytics-d8701b42caeb9f7f1de5fd45e7c3f3cf1724ebb6/ultralytics/yolo/v8/detect/train.py", line 54, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode, batch_size)
  File "/content/train_and_validation/ultralytics-d8701b42caeb9f7f1de5fd45e7c3f3cf1724ebb6/ultralytics/yolo/v8/detect/train.py", line 28, in build_dataset
    return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == 'val', stride=gs)
  File "/content/train_and_validation/ultralytics-d8701b42caeb9f7f1de5fd45e7c3f3cf1724ebb6/ultralytics/yolo/data/build.py", line 74, in build_yolo_dataset
    return YOLODataset(
  File "/content/train_and_validation/ultralytics-d8701b42caeb9f7f1de5fd45e7c3f3cf1724ebb6/ultralytics/yolo/data/dataset.py", line 39, in __init__
    super().__init__(*args, **kwargs)
  File "/content/train_and_validation/ultralytics-d8701b42caeb9f7f1de5fd45e7c3f3cf1724ebb6/ultralytics/yolo/data/base.py", line 72, in __init__
    self.labels = self.get_labels()
  File "/content/train_and_validation/ultralytics-d8701b42caeb9f7f1de5fd45e7c3f3cf1724ebb6/ultralytics/yolo/data/dataset.py", line 141, in get_labels
    raise ValueError(f'All labels empty in {cache_path}, can not start training without labels. {HELP_URL}')
ValueError: All labels empty in /content/train_and_validation/datasets/coco128-seg/labels/train2017.cache, can not start training without labels. See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

```

**Comment by mdvdv** [comment]
Hello. You need to replace all labels in val/train annotation files with 0. FastSAM is not intended for classification. In the annotation, as in yaml, only "0" class should be specified.

**Comment by mdvdv** [comment]
Not elegant, but works well
```python
def unlabel_annotation(ann_path: str, target: int = 0) -> str:
    undef_objs = []
    # Read the file with original annotation
    with open(ann_path, "r", encoding="utf-8") as file:
        objs = file.readlines()
    # Replace the class value with target
    for obj in objs:
        undef_objs.append(f"{target} {' '.join(obj.split()[1:])}")
    # Rewrite the annotation file
    with open(ann_path, "w", encoding="utf-8") as file:
        file.write("\n".join(undef_objs))

    return ann_path
```

**Comment by sunwoo76** [comment]
@mdvdv 

Hello :)

Have you tried to train the FastSAM with SA-1B dataset?

**Comment by mdvdv** [comment]
> @mdvdv 
> 
> Hello :)
> 
> Have you tried to train the FastSAM with SA-1B dataset?
> 

Hi, no, I'm studying the use of SA models in a narrow domain to detect out-of-distribution objects

**Comment by Linaom1214** [comment]
@mdvdv  thanks! I'm training the  model now!
